### ISSUE TITLE
Make walls randomly generate, yet allow a possible path

### ISSUE THREAD

**Issue by rishabhreng** [rishabhreng/processingGame#2]
should not be a labyrinth however
- also, figure out an efficient way to check for potential collision with wall and prevent such movement

**Comment by hermanb1** [comment]
Wall collision could be tested by having a global 2d array which stores the type of each square on the grid—enemy, open, player, goal, or wall. If the space the player or enemy is trying to move to is not a wall, then the movement proceeds as normal. Otherwise, the AI should choose another route, or the player should either be given another chance or lose a turn.
